CREATE TABLE IF NOT EXISTS public.ordenes_trabajo_detalle (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id bigint NULL,
  work_order_number text NULL,
  status text NULL,
  store_id bigint NULL,
  payload jsonb NOT NULL,
  fetched_at timestamptz NOT NULL DEFAULT now(),
  inserted_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ordenes_trabajo_detalle_source_id_idx
  ON public.ordenes_trabajo_detalle (source_id);

ALTER TABLE public.ordenes_trabajo_detalle DISABLE ROW LEVEL SECURITY;

-- Used by POST /api/sync-work-orders?mode=full for full-refresh TRUNCATE.
CREATE OR REPLACE FUNCTION public.truncate_ordenes_trabajo_detalle()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  TRUNCATE TABLE public.ordenes_trabajo_detalle;
END;
$$;
