CREATE TABLE IF NOT EXISTS public.ordenes_trabajo_raw (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id bigint NULL,
  payload jsonb NOT NULL,
  work_order_number text NULL,
  status text NULL,
  created_at timestamptz NULL,
  fetched_at timestamptz NOT NULL DEFAULT now(),
  inserted_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ordenes_trabajo_raw_source_id_idx ON public.ordenes_trabajo_raw (source_id);

ALTER TABLE public.ordenes_trabajo_raw DISABLE ROW LEVEL SECURITY;
